### ISSUE TITLE
Add continuous integration services

### ISSUE THREAD

**Issue by abitrolly** [nlprocby/RHVoice#1]
We need to add RHVoice repository to Travis on Linux and OS X and AppVeyor on Windows.

**Comment by yauhen-info** [comment]
I've added travis https://travis-ci.org/nlprocby/RHVoice for Mac and Linux. Let's wait for Windows support from travis and set it up, issue to follow https://github.com/travis-ci/travis-ci/issues/216

**Comment by abitrolly** [comment]
Can we have a separate status for OS X? For Windows support we need AppVeyor.
