### ISSUE TITLE
Add AppVeyor CI for compiling Windows versions

### ISSUE THREAD

**Issue by abitrolly** [nlprocby/RHVoice#7]
- [x] add testing services
- [x] add URLs to compiled artifacts

With AppVeyout we are not only able to test RHVoice + NVDA plugin compilation, we are also able to provide compiled binaries (artifacts) for download.

**Comment by yauhen-info** [comment]
@abitrolly, if you are familiar with the CI, could you edit the particular yml file to build the project and publish artifacts as you mentioned?

**Comment by abitrolly** [comment]
Yes. I can do that.

**Comment by sergey-tihon** [comment]
GitHub allow you add artifacts to the release with changelog for this release. [Sample](https://github.com/fsprojects/Paket/releases/tag/2.18.0)
It works very nice when everything is automated.

**Comment by yauhen-info** [comment]
Now build failes with the following tail:

```
scons: *** [build\windows\README.txt] Source `README' not found, needed by target `build\windows\README.txt'.
scons: building terminated because of errors.
Command exited with code 2

```

**Comment by abitrolly** [comment]
@YauhenMinsk work is in process. ;)

If you register official nlproc account through email at https://ci.appveyor.com/signup we will be able to change AppVeyor URL from https://ci.appveyor.com/project/YauhenMinsk/rhvoice/ to https://ci.appveyor.com/project/nlprocby/rhvoice/

**Comment by yauhen-info** [comment]
will do

**Comment by yauhen-info** [comment]
Seems it's build 

```
Generating code
Finished generating code
scons: done building targets.
Discovering tests...OK
Build success
```

**Comment by abitrolly** [comment]
Yes, and you can download the results from https://ci.appveyor.com/project/YauhenMinsk/rhvoice/build/0.5.1.13/artifacts

**Comment by yauhen-info** [comment]
fix version number setup for an artifact name,
now it looks like 'RHVoice-Windows-{version}.zip', so {version} is not properly set

**Comment by abitrolly** [comment]
@YauhenMinsk it is not trivial, so better open a new issue.

**Comment by abitrolly** [comment]
Fixed.
